name: 'Setup Python Environment'
description: 'Konfiguruje środowisko Python i instaluje zależności'

inputs:
  python-version:
    description: 'Wersja Pythona do użycia'
    required: true
    default: '3.10'
  install-test-deps:
    description: 'Czy instalować zależności testowe'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install dependencies and package
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ "${{ inputs.install-test-deps }}" = "true" ]; then
          pip install pytest pytest-cov
        fi
        pip install -e .