name: Dokumentacja VitePress

on:
  push: 
    branches: [ dev ]
    paths:
      - 'docs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/docs-build.yml'
      - '.github/actions/setup-pnpm/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'docs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/docs-build.yml'
      - '.github/actions/setup-pnpm/**'
  workflow_dispatch:  # Pozwala na ręczne uruchomienie workflow

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js and pnpm
      uses: ./.github/actions/setup-pnpm
      with:
        node-version: '20'
        pnpm-version: '9.12.3'

    - name: Build documentation
      run: pnpm docs:build